/*
CONTADOR =0
NUMERO =1

MIENTRAS NUMERO!=0  

    LEER "INTRODUZCA UN NUMERO, 0 PARA TERMINAR" => NUMERO
    SI NUMERO%2 == 0 CONTADOR ++

ACABAR MIENTRAS

LEER "CANTIDAD DE NUMEROS PARES" CONTADOR
*/