/*
CONTADORPAR=0
CONTADORIMPAR=0
NUMERO =1

MIENTRAS NUMERO!=0  

    LEER "INTRODUZCA UN NUMERO, 0 PARA TERMINAR" => NUMERO
    SI NUMERO%2 == 0 CONTADORPAR++
        SI NUMERO%2 != 0 CONTADORIMPAR++

ACABAR MIENTRAS

LEER "CANTIDAD DE NUMEROS PARES" CONTADORPAR
    "CANTIDAD DE NÚMEROS IMPARES" CONTADORIMPAR
*/